fakeeditor: update to compile on zig 0.15.1
Trying to build this extension, I got these errors:

```
install
└─ install fakeeditor_macos_aarch64
   └─ compile exe fakeeditor_macos_aarch64 ReleaseSmall aarch64-macos 1 errors
src/main.zig:86:26: error: root source file struct 'Io' has no member named 'getStdOut'
    const stdout = std.io.getStdOut().writer();
                   ~~~~~~^~~~~~~~~~
```

This is no longer defined; just create a stdout local variable and pass it around.

```
build.zig:34:10: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
        .root_source_file = b.path("src/main.zig"),
         ^~~~~~~~~~~~~~~~
```

Now you can to call `createModule` with these fields, and then pass that module into `createExecutable`.